service: sls

custom:
  settings:
    POSTS_TABLE: webRTC
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
        dir: offline/migrations

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: iamadmin
  environment: ${self:custom.settings}
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
            - dynamodb:DescribeTable
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
        Resource:
          - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.POSTS_TABLE}"

functions:
  createPost:
    handler: testRoute.createPost
    events:
    - http:
        path: /post
        method: post
  getPost:
    handler: testRoute.getPost
    events:
    - http:
        path: /post/{id}
        method: get
  # getAllPosts:
  #   handler: handler.getAllPosts
  #   events:
  #   - http:
  #       path: /posts
  #       method: get     


resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.POSTS_TABLE}



plugins:
  # - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline